const data= {
    items:[
        {
            _id:'1',
            name:'KFC Classic Pilau',
            image:'/images/pilau.avif',
            category: ' Rice',
            price: 50,
            vendor: 'KFC',
            rating: 4.8,
            numReviews: 10,
            description: 'A sumptous bowl of rice',
        },
        {
            _id:'1',
            name:'KFC Classic Pilau',
            image:'./images/pilau.avif',
            category: ' Rice',
            price: 50,
            vendor: 'KFC',
            rating: 4.8,
            numReviews: 10,
            description: 'A sumptous bowl of rice',
        },
        {
            _id:'2',
            name:'KFC Classic Pilau',
            image:'/images/pilau.avif',
            category: ' Rice',
            price: 50,
            vendor: 'KFC',
            rating: 4.8,
            numReviews: 10,
            description: 'A sumptous bowl of rice',
        },
        {
            _id:'1',
            name:'KFC Classic Pilau',
            image:'/images/pilau.avif',
            category: ' Rice',
            price: 50,
            vendor: 'KFC',
            rating: 4.8,
            numReviews: 10,
            description: 'A sumptous bowl of rice',
        },
        {
            _id:'1',
            name:'KFC Classic Pilau',
            image:'/images/pilau.avif',
            category: ' Rice',
            price: 50,
            vendor: 'KFC',
            rating: 4.8,
            numReviews: 10,
            description: 'A sumptous bowl of rice',
        },
        {
            _id:'1',
            name:'KFC Classic Pilau',
            image:'/images/pilau.avif',
            category: ' Rice',
            price: 50,
            vendor: 'KFC',
            rating: 4.8,
            numReviews: 10,
            description: 'A sumptous bowl of rice',
        },
    ],
};
